### ISSUE TITLE
更高阶的更安静的自动化

### ISSUE THREAD

**Issue by ZekerZhayard** [IAXRetailer/MCreator_Setup#1]
粗略看了一下代码，我不熟悉 Python，但觉得有些地方还能改进：
1. https://github.com/IAXRetailer/MCreator_Setup/blob/ad27d322c33f01019b43beb53f0c8e1b70c9bfbc/main.py#L109-L119
   比较想知道如果操作系统是 `Windows 8/8.1` `Windows Server 2008 (R2)` `Windows Server 2012 (R2)` `Windows Server 2016` 时能否正确提示；
1. https://github.com/IAXRetailer/MCreator_Setup/blob/ad27d322c33f01019b43beb53f0c8e1b70c9bfbc/main.py#L172
   这里大概没必要让用户选择，因为这个路径是通过 `USERPROFILE` 环境变量确定的，这个路径在 cmd 中可以表示为 `%USERPROFILE%\.mcreator\gradle\jdks`，Python 里应当也有等效的表达方式；
1. https://github.com/IAXRetailer/MCreator_Setup/blob/ad27d322c33f01019b43beb53f0c8e1b70c9bfbc/main.py#L186
   .NET Framework 有静默安装方式，无需与用户交互：加 `/q` 参数，即 `./ndp48-x86-x64-allos-enu.exe /q /norestart`
1. https://github.com/IAXRetailer/MCreator_Setup/blob/ad27d322c33f01019b43beb53f0c8e1b70c9bfbc/main.py#L210
   Proxifier 有静默安装方式：加 `/silent` 参数，即 `./ProxifierSetup.exe /silent`，参见 https://jrsoftware.org/ishelp/index.php?topic=setupcmdline
1. https://github.com/IAXRetailer/MCreator_Setup/blob/ad27d322c33f01019b43beb53f0c8e1b70c9bfbc/main.py#L213
   Proxifier 也无需让用户手动注册，只需要在注册表的 `HKEY_CURRENT_USER\Software\Initex\Proxifier\License` 中创建两个 `REG_SZ` 类型的键值对，参见 https://www.proxifier.com/docs/win-v4/install.html：
   - `Key`: `5EZ8G-C3WL5-B56YG-SCXM9-6QZAP`
   - `Owner`: `注册用户名随便写`
1. https://github.com/IAXRetailer/MCreator_Setup/blob/ad27d322c33f01019b43beb53f0c8e1b70c9bfbc/main.py#L246-L249
   Proxifier 导入配置也无需让用户手动导入，只需要启动 Proxifier 时加对应配置的路径作为参数即可：`./Proxifier.exe ./Minecraft.ppx silent-load`，参见 https://www.proxifier.com/docs/win-v4/profiles.html

**Comment by H2Sxxa** [comment]
好的，最近开学时间比较少，会找机会实现，谢谢炸鸭
对于第一个问题，我觉得可以来查询注册表，检测系统的确是下下策

**Comment by H2Sxxa** [comment]
暂时算是实现了，具体日后留观
https://github.com/IAXRetailer/MCreator_Setup/releases/tag/0.55
